### PR TITLE
Button text readability

### PR DESCRIPTION
**Pull request by bortkiewicz**
The current version, the text is too obscured

### CODE REVIEW

**Comment by bortkiewicz** [comment]
Would this help? I will make more prs if this doesn't (sorry)

**Comment by hanyuone** [comment]
Wait, what? Why are you changing the colour of the buttons? You could just change the colour of the text inside it, you know (I kinda want to keep the colour of the button, cause it fits with a cool scheme).

**Comment by bortkiewicz** [comment]
Okay.

**Comment by bortkiewicz** [comment]
you'll see a new pr soon

**Pull request closed without merging**
