### PR TITLE
Update styles.css

### PR DESCRIPTION
**Pull request by bortkiewicz**
Er... so this will affect all of the `button` subclasses, like mainbutton, etc.?

### CODE REVIEW

**Comment by hanyuone** [comment]
Yeah, that should be fine.

**Comment by hanyuone** [comment]
I added some code to fix the bug where the "Stats" box wasn't displaying properly.

**Comment by hanyuone** [comment]
Yes! I added a new mobs file (which we can do a lot with!)

**Comment by bortkiewicz** [comment]
Do you mind if i merge this? revert it if u want

**Pull request merged**
